### ISSUE TITLE
API pagination service

### ISSUE THREAD

**Issue by ipapandinas** [kudos-ink/portal#2]

**Comment by CJ13th** [comment]
There is a slight issue with doing pagination in Notion which is that it currently is not possible to access the total number of records via their API e.g no COUNT(id) type functionality (although we can get access to record totals through other means). There is also no way to query the database while passing in an offset e.g
query(params, offset). What is currently returned as a response from a query is an object with the following shape

```
export type QueryDatabaseResponse = {
    type: "page_or_database";
    page_or_database: EmptyObject;
    object: "list";
    next_cursor: string | null;
    has_more: boolean;
    results: Array<PageObjectResponse | PartialPageObjectResponse | PartialDatabaseObjectResponse | DatabaseObjectResponse>;
};

```

When polling in the cloud functions I query by doing something like

```
let response = await notionQueryTable(params);
let processResult = await processResponse(response);

while (processResult.has_more) {
    response = await notionQueryTable(params, response.next_cursor);
    processResult = await processResponse(data);
}
```

The query response from the Notion returns a `next_cursor` string which you can use to query again and get the next set of records that follow.

I bring this up because we may need to consider this when we think about pagination.

For example if someone browses to main issues list screen, which will be page 1, we will make a call to fetch the first set of records and then display the response. To be able to browse to page 3 though we need to have first made the call for the records from page 2, so that we can use `response.next_cursor` string for our query for the records for page 3.

So as it currently stands there is no way to skip from page 1 to page 10 for example, you can only go to page n+1 from the current page. 

So we can try a few options:

1. Don't have numbered pagination, only infinite scroll or simply have a "next page/ show more button" for a query.
2. Notion max results size is 100. So we could fetch 100 records, but only show the user 20 records per page. That way we can show pages 1..5 and then when they click to navigate to page 5, we make the next request for 100 records. 

Let me know what approach you think makes sense or if there is another way you can think of doing pagination with the current limitations.

**Comment by leapalazzolo** [comment]
Nice research! I don't think not having the total number of records right now is a big deal. We can figure out another way to calculate it if needed (more like a 'nice to have' feature for now).

About the lack of pagination, I think the 'infinite scroll' is a smart way to handle it. It's not a bad approach; I've seen OnlyDust using it.

For the next iteration, we might consider both aspects, but I'm cool with rolling with it as is for now.

**Comment by CJ13th** [comment]
I agree, I think infinite scroll makes the most sense for now too. But yeah lack of pagination is definitely another reason why we need our own database!
