### ISSUE TITLE
Language filter: Accuracy and values

### ISSUE THREAD

**Issue by leapalazzolo** [kudos-ink/portal#20]
I've tried to make the "language filter" dynamic by getting all the issues from the Notion and taking their "language repo" but I found some issues:

![image](https://github.com/kudos-ink/portal/assets/22482966/c54e174e-aa1c-4f97-8281-7a46332a975b)

#### Accuracy 

The approach of using that information isn't too accurate. Let's use the second issue from this repository as an example:

![image](https://github.com/kudos-ink/portal/assets/22482966/fe2310dd-760c-47d9-aa33-2a4cf45dddc3)

Currently, the repository has all these languages 
![image](https://github.com/kudos-ink/portal/assets/22482966/eafd5216-0f3a-4c0c-8f8f-91c848166ff1)

However, there's no way to determine the language required for the issue because it lacks labels, as seen in [this example](https://github.com/t3rn/t3rn/issues/1301).

While this method might work perfectly for repositories with only one language, it's not the most common case. This could compromise the user experience if the website displays issues not related to the selected language. Let's discuss potential solutions or adjustments to enhance accuracy and usability.

This problem doesn't affect other projects:
- OnlyDust shows repositories instead of issues. 
- RemoteOK and DeWork use filters based on "pre-defined values" that are selected when the task/offer is created

![image](https://github.com/kudos-ink/portal/assets/22482966/bac1163a-5cdb-46d7-810d-69ec19aaf09c)

![image](https://github.com/kudos-ink/portal/assets/22482966/3bb4195f-02b3-4686-b48c-4482064a5df5)

Some solutions:
- show repositories instead of issues
- keep the same behaviour accepting the lack of accuracy in some cases
- use this filter only if the issue has labels
- try to find the "keyword" in the title or description

#### Values

To generate a dynamic list of values in the filter, currently, I need to retrieve all the issues from Notion, which requires 45 sequential requests due to the 'cursor' limitation. As illustrated in the image below, this process is slow and may not scale well in the future, potentially triggering rate limits and hindering the success of other requests.
![image](https://github.com/kudos-ink/portal/assets/22482966/5fbcd78e-0e24-4cd9-96c7-0c05b480694a)

This is slow and won't scale in the future. This can prevent other requests from being successful because it can trigger the rate limit. 

Some solutions:
- use predefined values similar to RemoteOk
- take the languages from the request that gets the issues when the website loads for the first time (they won't be all, just a subset)
- save all the languages in a different backend service

**Comment by ipapandinas** [comment]
Nice investigation, I think that some compromises have to be made in view of our current stack.

I suggest keeping the current behaviour on accuracy and displaying the major languages of the project rather than the exact language of the issue's scope. So it's more like a trend.

Regarding the list of options available for the filter, I suggest proceeding like RemoteOK with static values.

**Comment by CJ13th** [comment]
So the Repo Language and Project Name fields in the main table are both relational fields from another Notion table which the API key can access. You can take a look at the table [here](https://polkadot-open-issues.notion.site/polkadot-open-issues/4b173a8695924fdb900fb57095b83b32?v=10b33b50bad14ae382b4537383cdef2c). It would be easier to query this table if you want to get a list of the languages which could appear since it's only one page of records. 

 I initially populated the languages field by using the GitHub API to the fetch language data for a repository, but I would only import languages where the code percentage for that repo was >= 10%.  This language data is currently static as the import was a one off script, so the languages data is not currently being monitored and updated by the cloud functions. I don't think it's likely the language data for a repo will change much, however it would be very simple to add another cloud function to monitor and update this, so I'll add this to the tasks.

Since the current languages data is static, I also think that for now, we should just proceed with hard coding the values for the filter options.

For the issue language, I don't think there is much we can do. As @leapalazzolo rightly points out, there is no sure-fire way to determine which language is needed to solve an issue if it's not labelled or otherwise made clearly obvious. So I also agree that we should just keep the current behaviour. In future, this problem might be mitigated if we can convince projects to use the issue template system we discussed.
