### ISSUE TITLE
Improve Next caching for the homepage and Notion fetch

### ISSUE THREAD

**Issue by ipapandinas** [kudos-ink/portal#38]
Consider using Tanstack SSR: https://tanstack.com/query/latest/docs/framework/react/guides/advanced-ssr

**Comment by leapalazzolo** [comment]
I have a simple but powerful solution to improve the website's data fetching to the repository-classification's json files (interests, languages and repositories filters) : use an **on-demand data revalidation**:


### on-demand data revalidation

![image](https://github.com/kudos-ink/portal/assets/22482966/8fc03cbf-4877-47bd-893a-913fc58fd8f3)

[https://nextjs.org/docs/app/building-your-application/caching#on-demand-revalidation](https://nextjs.org/docs/app/building-your-application/caching#on-demand-revalidation)

Data will be fetched and saved as a cache until we manually revalidate it. This is the most efficient way to do it according to our solution because:

1. our json files aren't updated to often
2.  we know when they're updated so we can trigger the revalidation in the same pipeline

We will validate the data as necessary, ensuring that revalidation occurs when required. Subsequent revalidation will only take place when deemed necessary again."

### solution

1. Define a tag for the filter's fetch
2. Define an endpoint with a simple authentication that will revalidate that tag
3. Make this call when the gh-pages' pipeline finishes in the repository-classification

**Comment by ipapandinas** [comment]
Agreed this is the "Next" way to go for performances. However we are using Notion third-party library to fetch data and according to the [documentation](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#fetching-data-on-the-server-with-third-party-libraries) we cannot benefit from an on-demand tagging revalidation system. This option is not listed in the [route segment config](https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#revalidate).

What I suggest is to use a direct fetch instead to have more flexibility with Next caching. This look like this in the [Notion documentation](https://developers.notion.com/reference/post-database-query):

```javascript
const options = {
  method: 'POST',
  headers: {
    accept: 'application/json',
    'Notion-Version': '2022-06-28',
    'content-type': 'application/json'
  },
  body: JSON.stringify({filter: 'string', start_cursor: 'string', page_size: 100})
};

fetch('https://api.notion.com/v1/databases/database_id/query', options)
  .then(response => response.json())
  .then(response => console.log(response))
  .catch(err => console.error(err));
```

Some suggestions for each steps:

1. Our tag can be **'contributions'**
2. A classic admin JWT auth token should be ok
3. Perfect!

**Comment by leapalazzolo** [comment]
Great! My initial solution only included the HTTP calls to the **repository-classification's JSON files* but I like the idea of extending it by adding a classic fetch to Notion's API. Let's do it!

**Comment by leapalazzolo** [comment]
I agree. Let's have a manual revalidation for the filters and a time-based for the issues (hourly).

**Comment by ipapandinas** [comment]
https://github.com/kudos-ink/portal/pull/46
